# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.0.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - run: npm install
      # - run: npm run build

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      # run tests!
      # - run: npm test
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.0.0

    working_directory: ~/repo

    steps:
      # - checkout
      # - run: npm install
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - run:
          name: Test
          command: npm test

      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
  component_test:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.0.0
      - image: circleci/redis:3.2-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      
      - run:
          name: build API
          command: npm run build

      - run:
          name: running API
          command: npm start
          background: true
      
      - run: sleep 5
      
      - run:
          name: run ping test
          command: curl $SERVER_URI:$SERVER_PORT

      # - run:
      #     name: run login test
      #     command: curl http://localhost:3000/login

      # - run:
      #     name: run logou test
      #     command: curl http://localhost:3000/logout

      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - component_test:
          requires:
            - test
          filters:
            branches:
              only: master
