# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.0.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      # Download and cache dependencies
      - restore_cache: 
          name: Restore Source
          keys: 
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - restore_cache:
          name: Restore Dependences
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - checkout

      - run: 
          name: Install Dependences
          command: npm install

      - save_cache:
          name: Save Source
          key: v1-dependencies-{{ checksum "package.json" }}
          paths: 
            - node_modules
      - save_cache: 
          name: Save Dependences
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

  unit_test:
    name: Unit Tests
    docker:
      - image: circleci/node:11.0.0

    working_directory: ~/repo

    steps:
      - restore_cache: 
          name: Restore Source
          keys: 
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - restore_cache:
          name: Restore Dependences
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Unit Tests
          command: npm test

  component_test:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.0.0
      - image: circleci/redis:3.2-alpine

    working_directory: ~/repo

    steps:
      - restore_cache: 
          name: Restore Source
          keys: 
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - restore_cache:
          name: Restore Dependences
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      
      - run:
          name: build API
          command: npm run build

      - run:
          name: running API
          command: npm start
          background: true
      
      - run: sleep 5
      
      - run:
          name: run ping test
          command: curl $SERVER_URI:$SERVER_PORT

      # - run:
      #     name: run login test
      #     command: curl http://localhost:3000/login

      # - run:
      #     name: run logou test
      #     command: curl http://localhost:3000/logout

      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests


workflows:
  version: 2
  install_build_test:
    jobs:
      - install
      - unit_test:
          requires:
            - install
          filters:
            branches:
              only: master
      - component_test:
          requires:
            - unit_test
          filters:
            branches:
              only: master
