# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.0.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      # Download and cache dependencies
      - restore_cache: 
          name: Restore Source
          keys: 
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - restore_cache:
          name: Restore Dependences
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - checkout

      - run: 
          name: Install Dependences
          command: npm install

      - save_cache:
          name: Save Source
          key: v1-dependencies-{{ checksum "package.json" }}
          paths: 
            - node_modules
      - save_cache: 
          name: Save Dependences
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

  unit_test:
    name: Unit Tests
    docker:
      - image: circleci/node:11.0.0

    working_directory: ~/repo

    steps:
      - restore_cache: 
          name: Restore Source
          keys: 
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - restore_cache:
          name: Restore Dependences
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Unit Tests
          command: npm test

  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.0.0

    working_directory: ~/repo

    steps:
      - restore_cache: 
          name: Restore Source
          keys: 
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - restore_cache:
          name: Restore Dependences
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      
      - run:
          name: build lib
          command: npm run build


workflows:
  version: 2
  install_build_test:
    jobs:
      - install
      - unit_test:
          requires:
            - install
          filters:
            branches:
              only: master
      - build:
          requires:
            - unit_test
          filters:
            branches:
              only: master
